version: "3.6"
services:
  # Master
  master-node:
    image: "binhvd/spark-cluster:0.17"
    hostname: master-node
    networks:
      - cluster-net
    ports:
      - 8088:8088
      - 8080:8080
      - 9870:9870
      - 18080:18080
      - 8888:8888

  # Workers
  worker:
    image: "binhvd/spark-cluster:0.17"
    networks:
      - cluster-net
    ports:
      - 8081:8081
    depends_on:
      - "master-node"

# Uses cluster-net network
networks:
  cluster-net:
